name: Android Build

on:
  push:
    branches:
      - main
      - dev
      - android_support

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          ndk: 26.1.10909125 # A recent NDK version compatible with API 35
          cmake: 3.30.3

      - name: Debug Environment Variables
        run: printenv

      - name: Debug Android Home and CMake
        run: |
          echo "ANDROID_HOME: ${{ env.ANDROID_HOME }}"
          echo "Listing CMake versions installed by setup-android action:"
          ls -l ${{ env.ANDROID_HOME }}/cmake/
          echo "-----------------"
          echo "Default system CMake version:"
          /usr/bin/cmake --version
          echo "-----------------"
          echo "CMake version configured by setup-android action:"
          ${{ env.ANDROID_HOME }}/cmake/3.30.3/bin/cmake --version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: app/platform/android

      - name: Build Android Release APK
        run: ./gradlew assembleRelease -Pandroid.injected.cmake.dir=${{ env.ANDROID_HOME }}/cmake/3.30.3/bin
        working-directory: app/platform/android

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: app/platform/android/build/outputs/apk/release/*.apk